print('\n')
first_name = input('What is your first name')
last_name = input('What is your last name')
address = input('What is your address')
city = input('What is your city')
state = input('What is your state')
post_code = input('What is your post code')
print('\n')
print(first_name,last_name)
print(address)
print(city,state,post_code)
